# Generated by Django 4.2.6 on 2023-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0006_userdetail_customerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='contact',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='contact',
            field=models.CharField(),
        ),
    ]
