# Generated by Django 4.2.6 on 2023-11-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0009_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
