# Generated by Django 4.2.6 on 2023-10-26 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoWorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('slots', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/space/hall')),
                ('is_available', models.BooleanField(default=False)),
                ('location', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoWorkBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.coworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('Capacity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/space/hall')),
                ('is_available', models.BooleanField(default=False)),
                ('location', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.conferencehall')),
            ],
        ),
    ]
