# Generated by Django 4.2.6 on 2023-10-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoWorkBooking',
            new_name='ConferenceBookingDate',
        ),
        migrations.RenameModel(
            old_name='ConferenceBooking',
            new_name='CoWorkBookingDate',
        ),
        migrations.AlterField(
            model_name='conferencebookingdate',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.conferencehall'),
        ),
        migrations.AlterField(
            model_name='coworkbookingdate',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.coworkspace'),
        ),
    ]
