# Generated by Django 4.2.6 on 2023-10-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_rename_coworkbooking_conferencebookingdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencehall',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='coworkspace',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
