# Generated by Django 4.2.6 on 2023-12-01 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0004_conferencehall_created_at_coworkspace_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceHallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.conferencehall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coworkbookingdate',
            name='space',
        ),
        migrations.DeleteModel(
            name='ConferenceBookingDate',
        ),
        migrations.DeleteModel(
            name='CoWorkBookingDate',
        ),
    ]
