# Generated by Django 4.2.6 on 2023-12-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_conferencehallbooking_remove_coworkbookingdate_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencehallbooking',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
