# Generated by Django 4.2.6 on 2023-12-05 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0010_alter_coworkspace_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkSpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('price', models.IntegerField(null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.coworkspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
