# Generated by Django 4.2.6 on 2023-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumcustomer',
            name='exp_date',
            field=models.DateField(),
        ),
    ]
