# Generated by Django 4.2.7 on 2023-11-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotificationcreate',
            name='notification_type',
            field=models.CharField(choices=[('register', 'register'), ('cospace', 'cospace'), ('conference', 'conference')], default='space', max_length=20),
        ),
    ]
