# Generated by Django 4.2.7 on 2023-11-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_adminnotificationcreate_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotificationcreate',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
